### ISSUE TITLE
Pull_character dies a horrible death if a character's ship name uses non-ASCII characters.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#229]
Ship Name: カリバチ™

Stack Trace:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/core/src/brave/core/key/model.py", line 202, in pull
    if not self.pull_character(char):
  File "/home/core/src/brave/core/key/model.py", line 107, in pull_character
    info = api.eve.CharacterInfo(self, characterID=info.characterID)
  File "/home/core/src/brave/core/util/eve.py", line 244, in __call__
    data = xml(data)['eveapi']
  File "/home/core/local/lib/python2.7/site-packages/relaxml-0.1.3-py2.7.egg/relaxml/converter.py", line 34, in xml
    string = str(data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 288-292: ordinal not in range(128)
```

**Comment by jboning** [comment]
https://github.com/zachwill/relaxml/blob/master/relaxml/converter.py#L31 sigh.

**Comment by jboning** [comment]
P.S. it would be great to have a test to prevent regressions :) I'll do this when I get a chance, unless you beat me to it
